[plugin]
prepend_previewers = [
	{ mime = "text/csv", run = "rich-preview" },
	{ mime = "text/markdown", run = "rich-preview" },
	{ mime = "text/x-rst", run = "rich-preview" },
	{ mime = "application/x-ipynb+json", run = "rich-preview" },
	{ mime = "application/json", run = "rich-preview" },
	#	{ name = "*.lang_type", run = "rich-preview"} #for particular language files eg. .py, .go., .lua, etc.
]

[mgr]
linemode = "size_and_mtime"

# 文本编辑使用 nvim 打开
[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
